service:
  twitter:
    header: Bearer AAAAAAAAAAAAAAAAAAAAAPErJwEAAAAAaVaHf%2FebQpB%2BxZ8P8SfrYu1dmJQ%3DTYaWglF2ULQYNUDa09rYhCzFx4Zr6kNZrLVEOWBBrJBWmDK560
    url: https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=
    param: retweet_status=false&tweet_mode=extended
    paramInitial: tweet_mode=extended&since=2020-09-01&count=200
    home_url: https://twitter.com/
    fixedDelay: 1800000
    initialDelay: 100000
  facebook:
    fixedDelay: 7200000
    initialDelay: 100000
  news:
    fixedDelay: 60000
    initialDelay: 900000
  cache:
    fixedDelay: 1620000
    initialDelay: 100000
